[project]
name = "study-p-value"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "hyman9090", email = "hyman9090@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "scipy>=1.18.1",
]

[project.scripts]
study-p-value = "study_p_value:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
